# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='/haiku/')),
                ('line_one', models.CharField(max_length=64)),
                ('line_two', models.CharField(max_length=64)),
                ('line_three', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Haiku',
                'verbose_name_plural': "Haiku's",
            },
        ),
    ]
