# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiku_app', '0002_remove_haiku_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='haiku',
            name='image',
            field=models.ImageField(blank=True, upload_to='/media/haiku/'),
        ),
        migrations.AddField(
            model_name='haiku',
            name='url_title',
            field=models.CharField(default='hello', max_length=32),
        ),
    ]
