# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='url_title',
            field=models.CharField(default='title', max_length=256, unique=True),
        ),
    ]
